# Assignment 1: Python Fundamentals, NumPy, and Pandas

---

## Tasks

### Task 0: GitHub and Jupyter Notebook for submission (2p)

Set up a public GitHub repository with the following folder structure:

```
your-repo-name/
└── assignments/
    └── assignment1/
        └── assignment1.ipynb
```

Your submission for this assignment is the Jupyter notebook file placed inside the `assignments/assignment1/` folder. The repository must be public so that the peer reviewers and the instructor can access it. (1p)

The submission should be a clean, well-organized Jupyter notebook that is easy to follow. This means clear separation between tasks, meaningful markdown headings or comments for each task, and no unnecessary clutter. (1p)

### Task 1: A list of dictionaries (1p)



In [1]:
#The list of raw transaction records given:
transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

#print(transactions)
#type(transactions)

#a) Filter out invalid transactions where the price is zero or the quantity is negative.

#I filter based on the rules and create a new list of dictionaries which contain only the ones 
#which fulfil the criteria.
transactions_new =[]   #create an empty list which is then filled next
for trans in transactions:
    if trans["price"] > 0 and trans["quantity"]>=0:
        transactions_new.append(trans)

print("filtered out invalid transactions:")
print(transactions_new)
    


filtered out invalid transactions:
[{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU'}, {'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US'}, {'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU'}, {'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC'}]


In [2]:
#b) For each remaining transaction, compute a new field `total` = `price * quantity`.
# I perform this creating a new field by looping across each dictionary in the list 
for trans_new in transactions_new:
    trans_new["total"]= trans_new["price"] * trans_new["quantity"]

for trans_new in transactions_new:
    print(trans_new)




{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU', 'total': 2400}
{'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US', 'total': 1050}
{'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU', 'total': 1200}
{'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC', 'total': 750}


In [3]:
#c) Group the valid transactions by `region` and compute the total revenue per region. 
#Store the result in a dictionary.

regional_revenue = {} # this creates an empty dictionary
for reg in transactions_new: #this goes through each item in the transactions_new list
    if reg["region"] not in regional_revenue: #this checks whether the region exists in the new dictionary
        regional_revenue[reg["region"]]= 0   #
        regional_revenue[reg["region"]] +=reg["total"]

print(regional_revenue)
    


{'EU': 2400, 'US': 1050, 'APAC': 750}


In [4]:
# d) Print the region with the highest total revenue and its value using an f-string.  

def get_value(k): 
    return regional_revenue[k]
    
max_region = max(regional_revenue, key=get_value)
#print(max_region)

print(f"\nRegion with the highest total revenue is {max_region} with total value of {regional_revenue[max_region]}")


Region with the highest total revenue is EU with total value of 2400


### Task 2: Creating a function (1p)



In [14]:
# the list of daily sales figures (in euros) for a two-week period given:

sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

#print(sales)
#type(sales)

#Write a function called summarise_sales that takes a list of daily sales values and returns a dictionary containing:

from statistics import mean 

#I have used R a lot and was surprised to learn that Python does not a built-in mean
#function. I took the easy way out and imported it from the statistics module. 
#However, I also calculated average manually. len function is the same as in R.

def summarise_sales(x):
    total = sum(x)
    average = mean(x)
    average_manual= sum(x)/len(x)
    best_day = x.index(max(x))+1
    worst_day = x.index(min(x))+1
    above_average_count = len([day for day in x if day > average])
    return {"total": total, "average": average, "average manual": average_manual, "best_day": best_day, "worst_day": worst_day, "above_average_count": above_average_count}
  
result = summarise_sales(sales)

print(result)
type(result)

{'total': 20510, 'average': 1465, 'average manual': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}


dict

### Task 3: Loops (1p)



In [6]:
#the list of student records given

students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

#print(students)
#type (students)
#len(students)

#Using for loops and if statements, perform the following:
#a) Create a new list called passing that contains only the names of students with a grade of 50 or above. Print the list.

passing= []
for student in students:
    if student ["grade"] >=50:
        #print(student["name"])
        passing.append((student["name"]))
print("names of students with a grade of 50 or above:") 
print(passing) 

print(" ")
print(" ")
    
# b) Loop through the students and print a status message for each. If the student's grade is 80 or above, print "[name]: 
#Excellent"; if between 50 and 79, print "[name]: Pass"; otherwise print "[name]: Fail".
print("Status message for students:")
for student in students:
    if student ["grade"] >=80:
        print(f"{student["name"]}: Excellent")
    elif student ["grade"] >=50:
        print(f"{student["name"]}: Pass")
    else:
        print(f"{student["name"]}: Fail")




names of students with a grade of 50 or above:
['Anna', 'Erik', 'Mia', 'Sara', 'Tom', 'Nina', 'Olli']
 
 
Status message for students:
Anna: Excellent
Erik: Pass
Mia: Excellent
Leo: Fail
Sara: Pass
Tom: Pass
Nina: Excellent
Olli: Pass


In [7]:
#c) Count how many students have an attendance rate below 0.80. Print the count.

attendance_80 = 0  #I create a new variable and set it to zero. The for loop compares each attendace rate and
# in case the if statement returns true, I add +1 to the variable. 

for student in students:
    if student ['attendance'] <0.80:
        attendance_80 += 1

print("Number of students with attendance rate below 80:")
print(attendance_80)

print(" ")
  
#d) Find the student with the highest grade using a loop (do not use max()). Print the student's name and grade.

highest_grade = students[0] ["grade"]
best_student = students[0] ["name"] 

for student in students:
    if student ['grade'] >highest_grade:
        highest_grade = student ['grade']
        best_student = student ['name']

print("Student with the highest grade using a loop:")
print(f"{best_student}: {highest_grade}")
    
    
#e) Now find the student with the highest grade using max(). Print the student's name and grade.

print(" ")

best_student = max(students, key=lambda student: student['grade'])
#print(best_student)
print("Student with the highest grade using max():")
print(f"{best_student['name']}: {best_student['grade']}")   

Number of students with attendance rate below 80:
4
 
Student with the highest grade using a loop:
Nina: 95
 
Student with the highest grade using max():
Nina: 95


### Task 4: Class and methods (1p)



In [8]:
#The constructor provided

class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

#  a) A method add_asset(ticker, shares, price_per_share) that adds a new asset or updates the number 
    #of shares if the ticker already exists (in which case the price should also be updated).  
    
    def add_asset(self, ticker, shares, price_per_share):
        #self.holdings[ticker] = {"shares": shares,  "price_per_share": price_per_share} #creates a dictionary 
        # which is used below to create a dictionary always when the ticker is not in holdings: 
        if ticker not in self.holdings: #checks if the ticker already exists
            self.holdings[ticker] ={"shares": shares,  "price_per_share": price_per_share}
        else:
            self.holdings[ticker]["shares"] =shares
            self.holdings[ticker]["price_per_share"] =price_per_share               

#b) A method total_value() that returns the total market value of the portfolio.
    def total_value(self):
        total_value = 0
        for ticker in self.holdings:
            asset_value = self.holdings[ticker]["shares"] * self.holdings[ticker]["price_per_share"]
            total_value += asset_value
        return total_value


#c) A method most_valuable() that returns 
#the ticker of the asset with the highest total value (shares × price).
    def most_valuable(self):
        most_valuable_asset = max(self.holdings, key=lambda ticker: 
                                  self.holdings[ticker]["shares"] * self.holdings[ticker]["price_per_share"])
        return most_valuable_asset
        
      
#d) A __str__ method that returns a readable summary of the portfolio, 
#including the owner's name, the number of assets, and the total value.
    def __str__(self):
        return f"Owner: {self.owner}, Assets: {len(self.holdings)},  Total value: {self.total_value()}"



#Create an instance, add at least three assets, and demonstrate all methods with printed output.

#creating a new instance called portfolio_new where "test" is stored as self.owner. So now Python knows to use
#portfolio_new in this class. So self= portfolio_new

portfolio_new = Portfolio("test")

#Adding three assets with the add_asset method:
portfolio_new.add_asset("ABCD", 10, 100)
portfolio_new.add_asset("EFGH", 20, 140)
portfolio_new.add_asset("IJKL", 30, 160)

print("Total value of portfolio:")
print(portfolio_new.total_value())

print("")

print("Most valuable asset:")
print(portfolio_new.most_valuable())

print("")
#this is using the __str__ method to print a summary of the portfolio:

print(portfolio_new)   

Total value of portfolio:
8600

Most valuable asset:
IJKL

Owner: test, Assets: 3,  Total value: 8600


### Task 5: Importing a module (1p)

.

In [9]:


from datetime import datetime
#Using the `datetime` module, parse each date string into a `datetime.date` object.

#The list of order dates (as strings) and product names given:
orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]


#type(orders)
#print(orders)

#note to self: orders are tuples, not dictionaries. So I cannot mofify it like I could dictionaries.

#Using the datetime module, parse each date string into a datetime.date object. 

orders_new = [] #Create new list
for order in orders:
    date= datetime.strptime(order[0] , "%Y-%m-%d").date() #parsing
    orders_new.append((date, order[1])) #fill in the new list

#print(orders_new)

#Compute and print the number of days between the earliest and latest order.

highest= max(orders_new, key=lambda date: date[0])
#print(highest)

lowest= min(orders_new, key=lambda date: date[0])
#print(lowest)

difference = highest[0]-lowest[0]

print(f"\nNumber of days between the earliest and latest order is {difference.days}")  


# These websites gave  excellent explanations of the datetime tool https://mimo.org/glossary/python/datetime and 
#https://www.datacamp.com/tutorial/converting-strings-datetime-objects




Number of days between the earliest and latest order is 80


### Task 6: Array Operations and Broadcasting (1p)



In [10]:
import numpy as np

revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]])

revenue

#a) Compute and print the total annual revenue for each year (i.e., row sums). Use the axis parameter.
total_annual_revenue= np.sum(revenue, axis=1)   #np.sum axis parameter defines whether the function calculates
#row sums (axis=1) or column sums (axis=0)

print("Total annual revenue for each year:")
print(total_annual_revenue)

print("")

#b) Compute the mean quarterly revenue across all years (i.e., column means).
#https://numpy.org/doc/2.2/reference/generated/numpy.mean.html
#the first example shows how to calculate column means
mean_quarterly_revenue =np.mean(revenue, axis=0)

print("Average quarterly revenue:")
print(mean_quarterly_revenue)

print("")

#c) Using broadcasting, apply a growth adjustment to the 2024 row by multiplying it element-wise with the array 
#[1.05, 1.03, 1.08, 1.02]. Print the adjusted values.

# First I read this from the NumPy user guide: https://numpy.org/doc/stable/user/basics.broadcasting.html
#Then I used an example from the lectures

growth_adjustment = np.array([1.05, 1.03, 1.08, 1.02])
adjusted2024values = revenue[-1,: ] * growth_adjustment

print("Growth adjusted values:")
print(adjusted2024values)

print("")

#d) Use boolean indexing to find and print all quarterly 
#revenue values that exceed 250 (thousands of euros).

#really helpful website: https://www.datacamp.com/doc/numpy/filtering-arrays

filtered_revenue = revenue[revenue >250]
print("Filtered revenues:")
print(filtered_revenue)



Total annual revenue for each year:
[ 880  950 1080]

Average quarterly revenue:
[226.66666667 260.         206.66666667 276.66666667]

Growth adjusted values:
[262.5 298.7 248.4 316.2]

Filtered revenues:
[260 270 290 310]


### Task 7: Pandas (1p)



In [16]:

#Creating the dataframe

import pandas as pd
data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}

data_df=pd.DataFrame(data)

#a) Add a new column salary_per_year_exp computed as salary / years_exp. Round to the nearest integer.
#how to round up: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.round.html

data_df["salary_per_year_exp"]=(data_df["salary"]/data_df["years_exp"]).round(0)
#print(data_df)

#b) Sort the DataFrame by performance_score in descending order and print the top 3 employees.
#https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html
#df.sort_values(by="col1", ascending=False)

data_sorted =data_df.sort_values(by=["performance_score"], ascending=False)
print("The top 3 employees:")
print(data_sorted.head(3))
print("")

#c) Using .loc, select all employees in the Finance department with a performance score above 4.0. 
#Print the result.

print("employees in the Finance department with a performance score above 4.0:")
print(data_df.loc[(data_df["department"]=="Finance") & (data_df["performance_score"]>4.0)])
print("")
print("")

#d) Rename the column years_exp to experience_years using the .rename() method.
#https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html
data_df.rename(columns={"years_exp": "experience_years"}, inplace=True) 
print("Column title changed")
print(data_df)
#by using inplace=True I do not have create a new dataframe. But I can also do that:

#data_df_new=data_df.rename(columns={"years_exp": "experience_years"})

#e) Using .iloc, select and print the salary and performance score columns for the first four employees.

print("the salary and performance score columns for the first four employees")
print(data_df.iloc[0:4, [2,4]])

The top 3 employees:
  employee department  salary  years_exp  performance_score  \
5      Tom         IT    5100          8                4.9   
2      Mia    Finance    4800          7                4.5   
0     Anna    Finance    4500          5                4.2   

   salary_per_year_exp  
5                638.0  
2                686.0  
0                900.0  

employees in the Finance department with a performance score above 4.0:
  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2   
2      Mia    Finance    4800          7                4.5   

   salary_per_year_exp  
0                900.0  
2                686.0  


Column title changed
  employee department  salary  experience_years  performance_score  \
0     Anna    Finance    4500                 5                4.2   
1     Erik  Marketing    4000                 3                3.8   
2      Mia    Finance    4800                 7        

### Task 8: More Pandas (1p)



In [12]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)


In [13]:
#a) Create a DataFrame with columns: `date`, `visitors`, `conversion_rate`, and `avg_order_value`. 
#Set `date` as the index.

data={"date": days, "visitors": visitors, "conversion_rate": conversion_rate, "avg_order_value": avg_order_value}
data_df=pd.DataFrame(data)
#data_df

#setting the date as index so instead of 0,1,2... we use the date
data_df = data_df.set_index("date")
data_df

#b) Compute two new columns: `conversions` (= visitors × conversion_rate, 
#rounded to the nearest integer) and `daily_revenue` (= conversions × avg_order_value).

data_df["conversions"]=(data_df["visitors"]*data_df["conversion_rate"]).round(0)
data_df["daily_revenue"]=data_df["conversions"]*data_df["avg_order_value"]

data_df


,visitors,conversion_rate,avg_order_value,conversions,daily_revenue
date,,,,,
2025-01-06,206,0.0645,64.30,13.0,835.90
2025-01-07,472,0.0578,48.44,27.0,1307.88
2025-01-08,437,0.0756,43.26,33.0,1427.58
2025-01-09,221,0.0339,43.61,7.0,305.27
2025-01-10,563,0.0679,49.39,38.0,1876.82
2025-01-11,288,0.0511,46.07,15.0,691.05
2025-01-12,302,0.0339,72.90,10.0,729.00
2025-01-13,273,0.0300,42.82,8.0,342.56
2025-01-14,333,0.0499,50.33,17.0,855.61
